Address JNI C compilation warnings
IBM/OpenJCEPlus pull request #117
Opened 2024-07-01 17:20 UTC by jasonkatonica

There are currently numerous JNI C compilation warnings present. This update addresses each of the warnings including the following changes:

1. Various methods needed a void argument instead of empty parentheses.

1. Prototypes were added for various methods. Specifically function pointers in use needed to have associated function pointer prototypes.

1. A mixture of unsigned long and signed long values were present. Output lengths changed are output lengths and are believed to be unsigned.

1. A few method are not in use such as `JCC_HKDF_Extract`, `JCC_HKDF_Expand`, and `JCC_HKDF` are not in use and were removed.

Signed-off-by: Jason Katonica <katonica@us.ibm.com>

2024-07-01 18:53 UTC, johnpeck-us-ibm requested changes
Missed the copyright on jgskit.mak

2024-07-01 19:00 UTC, jasonkatonica commented
> Missed the copyright on jgskit.mak

Copyright should now be updated in this file. This update was also done in other release branches for this change.

2024-07-01 19:33 UTC, jasonkatonica commented
I also updated the copyright in GCM.c as it was incorrect in the various releases.

2024-07-02 13:05 UTC, johnpeck-us-ibm approved these changes

2024-07-03 13:51 UTC, merged