Print stack trace from all failures of multithreaded tests
IBM/OpenJCEPlus pull request #147
Opened 2024-07-31 14:16 UTC by KostasTsiounis

There was only an assertion that there weren't any failures as part of each test. If any failures had occurred, they weren't saved or printed.

The execution of the tests is changed to return the potential failures, instead of directly failing. Said failures are printed before the overall multithreaded test fails.

Signed-off-by: Kostas Tsiounis <kostas.tsiounis@ibm.com>

2024-07-31 19:55 UTC, jasonkatonica requested changes
Seems the copyrights need to be updated in these two files. Other then that I did not have any specific comments.

2024-08-01 13:12 UTC, KostasTsiounis commented
> Seems the copyrights need to be updated in these two files. Other then that I did not have any specific comments.

Copyrights updated.

2024-08-01 15:17 UTC, jasonkatonica approved these changes
LGTM

2024-08-08 16:25 UTC, johnpeck-us-ibm approved these changes

2024-08-08 17:30 UTC, jasonkatonica commented
x86_64_linux, ppc64le_linux, s390x_linux, x86_64_windows

2024-08-08 17:31 UTC, merged