Fix warnings related to dangling comments and lossy conversions
IBM/OpenJCEPlus pull request #268
Opened 2024-10-17 18:47 UTC by jasonkatonica

Recently numerous warnings have displayed related to lossy conversions and dangling `javadoc` comments.

This update ensures that there are no dangling `javadoc` comments these changes fall into various categories such as unused code that has `javadoc` comments embedded, empty `javadoc` comments, duplicate `javadoc` comments, or javadoc comments that are not located above a declaration.

Updates were also made to `XDHPublicKeyImpl`, `BaseTestChaCha20KAT`, and `BaseTestChaCha20NoReuse` to explicitly cast an int to a byte OR make use of a common utility function `BaseUtils.hexStringToByteArray` that does not have such a lossy conversion present.

While fixing dangling comments one test `testRSASignatureSHA512_256` was found to be commented out. It appears to execute correctly and does seem like a valid test so this test was uncommented.

Two spaces found in the pom.xml were removed for consistency.

Signed-off-by: Jason Katonica <katonica@us.ibm.com>

2024-10-18 14:53 UTC, johnpeck-us-ibm approved these changes

2024-10-18 15:08 UTC, KostasTsiounis requested changes

2024-10-18 18:59 UTC, jasonkatonica commented on src/main/java/com/ibm/crypto/plus/provider/PSSParameters.java
> - * </pre>
Yes agreed when using html we should close the `<pre>` tag to be cleaner. I also noticed that the `javadoc` was missing leading `* `values on each line so i added those too in the latest commit https://github.com/IBM/OpenJCEPlus/pull/268/commits/8e3ffae5d89087120efef46f43d481510b57c423

2024-10-18 18:59 UTC, jasonkatonica commented on src/test/java/ibm/jceplus/junit/base/BaseTestTruncatedDigest.java
> +            // TODO Auto-generated catch block
Yes I removed this comment and others exactly or very similar to this in commit https://github.com/IBM/OpenJCEPlus/pull/268/commits/8e3ffae5d89087120efef46f43d481510b57c423

2024-10-18 19:10 UTC, KostasTsiounis approved these changes
LGTM

2024-10-22 14:01 UTC, jasonkatonica commented
x86_64_linux, ppc64le_linux, s390x_linux, x86_64_windows

2024-10-22 17:49 UTC, taoliult approved these changes
LGTM

2024-10-22 17:58 UTC, merged