Makefile improvements
IBM/OpenJCEPlus pull request #274
Opened 2024-10-22 14:05 UTC by KostasTsiounis

* consider platforms alphabetically
* correct link command for z/OS
* reuse macros
* fix parallel builds
* improve command readability
* support EXTERNAL_HEADERS=true in all platforms

Co-authored-by: Keith W. Campbell <keithc@ca.ibm.com>
Co-authored-by: Kostas Tsiounis <kostas.tsiounis@ibm.com>
    
Signed-off-by: Kostas Tsiounis <kostas.tsiounis@ibm.com>

2024-10-22 17:38 UTC, johnpeck-us-ibm approved these changes

2024-10-23 13:01 UTC, jasonkatonica requested changes
It would be good also if we could do a dif between various makefiles to make them as consistant as possible in format so they are easier to maintain. I know you have done this in the past but just mentioning it as a general comment in case.

2024-10-23 13:01 UTC, jasonkatonica commented on src/main/native/jgskit.win64.mak
> +$(HOSTOUT)/%.obj: %.c
Some targets have a space before : and some do not. Do we want to make these consistant?

2024-10-23 13:41 UTC, KostasTsiounis commented on src/main/native/jgskit.mac.mak
> +	test -d ${@D} || mkdir -p ${@D} 2>/dev/null
Yes, `test -d` returns true or false based on whether the directory exists, and only if it doesn't is the second part of the logical expression executed (i.e., the `mkdir` command).

2024-10-23 13:42 UTC, KostasTsiounis commented on src/main/native/jgskit.mac.mak
> +		-fPIC \
The arguments of commands are intentionally further indented to indicate that they depend on the command above. Is that OK?

2024-10-23 13:43 UTC, KostasTsiounis commented on src/main/native/jgskit.mac.mak
> +	echo "Compiling headers"
Changed everywhere.

2024-10-23 13:43 UTC, KostasTsiounis commented on src/main/native/jgskit.win64.mak
> +		$(DEBUG_FLAGS) \
Same as above.

2024-10-23 14:06 UTC, KostasTsiounis commented
> It would be good also if we could do a dif between various makefiles to make them as consistant as possible in format so they are easier to maintain. I know you have done this in the past but just mentioning it as a general comment in case.

I have rechecked after the latest changes and tried to make them as similar as possible. Let me know if you see something that we could further change.

2024-10-23 14:06 UTC, jasonkatonica requested changes
Just one small spot i saw here.

2024-10-23 14:06 UTC, jasonkatonica commented on src/main/native/jgskit.mac.mak
> +		-fPIC \
OK that makes sense now that you mention it to indent the arguments to the compiler to make it easier to read. This seems OK to me.

2024-10-23 14:06 UTC, jasonkatonica commented on src/main/native/jgskit.mac.mak
> +	echo "Compiling headers"
Looks good to me.

2024-10-23 14:06 UTC, jasonkatonica commented on src/main/native/jgskit.mac.mak
> +${HOSTOUT}/%.o: %.c
Space before this :

2024-10-23 14:12 UTC, jasonkatonica approved these changes
LGTM

2024-10-23 16:02 UTC, jasonkatonica commented
x86_64_linux, ppc64le_linux, s390x_linux, x86_64_windows

2024-10-23 16:03 UTC, merged